services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend  # Path to your backend directory
    container_name: backend
    ports:
      - "5001:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./app   # Path to your React app directory
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
